const defaultProducts = [
    {
        id: 1,
        name: "SUPER OFFER 9",
        category: "pack",
        price: 150,
        image: "https://res.cloudinary.com/dvq4ieugm/image/upload/v1773436653/gsn-products/1773436652575-Artboard_17_lshv0d.png",
        desc: "BULK MASS 2.5KG 5X MONODOSE CREATINE MONOHYDRATE 200G SHAKRE 700ML",
        benefits: ["Produit authentique GSN", "Livraison rapide 24/48h", "100% Authentique"],
        flavors: ["chocolate milkshake", "vanilla milkshake"],
        sizes: ["2.5kg"],
        bestSeller: false
    },
    {
        id: 2,
        name: "SUPER OFFER 8",
        category: "pack",
        price: 110,
        image: "https://res.cloudinary.com/dvq4ieugm/image/upload/v1773436622/gsn-products/1773436621826-Artboard_16_v2k4pr.png",
        desc: "carbo max 3kg 5X MONODOSE CREATINE MONOHYDRATE 200G SHAKRE 700ML",
        benefits: ["Produit authentique GSN", "Livraison rapide 24/48h", "100% Authentique"],
        flavors: ["fruit punch"],
        sizes: ["3kg"],
        bestSeller: false
    },
    {
        id: 3,
        name: "SUPER OFFER 7",
        category: "pack",
        price: 150,
        image: "https://res.cloudinary.com/dvq4ieugm/image/upload/v1773436593/gsn-products/1773436592277-Artboard_15_ngzpys.png",
        desc: "pure whay 900G 5X MONODOSE CREATINE MONOHYDRATE 200G SHAKRE 700ML multi vitamins",
        benefits: ["Produit authentique GSN", "Livraison rapide 24/48h", "100% Authentique"],
        flavors: ["chocolate", "vanilla"],
        sizes: ["900kg"],
        bestSeller: false
    },
    {
        id: 4,
        name: "SUPER OFFER 6",
        category: "pack",
        price: 115,
        image: "https://res.cloudinary.com/dvq4ieugm/image/upload/v1773436551/gsn-products/1773436550524-Artboard_14_fbobcc.png",
        desc: "Big MASS gainer 1KG 5X MONODOSE CREATINE MONOHYDRATE 200G SHAKRE 700ML peanut butter multi vitamins",
        benefits: ["Produit authentique GSN", "Livraison rapide 24/48h", "100% Authentique"],
        flavors: ["chocolate", "vanilla"],
        sizes: ["1kg"],
        bestSeller: false
    },
    {
        id: 5,
        name: "SUPER OFFER 5",
        category: "pack",
        price: 240,
        image: "https://res.cloudinary.com/dvq4ieugm/image/upload/v1773436459/gsn-products/1773436458469-Artboard_13_j4nysc.png",
        desc: "pure whay 2kG 5X MONODOSE CREATINE MONOHYDRATE 200G SHAKRE 700ML mag+ b-complex zinc bisglycinate fish oil omega-3",
        benefits: ["Produit authentique GSN", "Livraison rapide 24/48h", "100% Authentique"],
        flavors: ["CHOCOLATE", "VANILLA", "strawberry"],
        sizes: ["2kg"],
        bestSeller: false
    },
    {
        id: 6,
        name: "SUPER OFFER 4",
        category: "pack",
        price: 210,
        image: "https://res.cloudinary.com/dvq4ieugm/image/upload/v1773436385/gsn-products/1773436384823-Artboard_12_rx7hqq.png",
        desc: "BULK MASS 5KG 5X MONODOSE CREATINE MONOHYDRATE 200G SHAKRE 700ML",
        benefits: ["Produit authentique GSN", "Livraison rapide 24/48h", "100% Authentique"],
        flavors: ["CHOCOLATE MILKSHAKE", "VANILLA MILKSHAKE"],
        sizes: ["5kg"],
        bestSeller: false
    },
    {
        id: 7,
        name: "SUPER OFFER 3",
        category: "pack",
        price: 100,
        image: "https://res.cloudinary.com/dvq4ieugm/image/upload/v1773436312/gsn-products/1773436311451-Artboard_11_ycc0cz.png",
        desc: "creapure 300g shakre 700ml",
        benefits: ["Produit authentique GSN", "Livraison rapide 24/48h", "100% Authentique"],
        flavors: ["NON"],
        sizes: ["0.3kg"],
        bestSeller: false
    },
    {
        id: 8,
        name: "SUPER OFFER 2",
        category: "pack",
        price: 180,
        image: "https://res.cloudinary.com/dvq4ieugm/image/upload/v1773436227/gsn-products/1773436226208-Artboard_10_wv4px5.png",
        desc: "BIG MASS GAINER 3KG 5X MONODOSE CREATINE MONOHYDRATE 200G SHAKRE 700ML PEANUT BUTTER multi vitamins",
        benefits: ["Produit authentique GSN", "Livraison rapide 24/48h", "100% Authentique"],
        flavors: ["CHOCOLATE", "VANILLA", "strawberry"],
        sizes: ["3kg"],
        bestSeller: false
    },
    {
        id: 9,
        name: "SUPER OFFER 1",
        category: "pack",
        price: 160,
        image: "https://res.cloudinary.com/dvq4ieugm/image/upload/v1773435941/gsn-products/1773435940156-Artboard_1_lowgy8.png",
        desc: "2X CREAPURE MONOHYDRATE",
        benefits: ["Produit authentique GSN", "Livraison rapide 24/48h", "100% Authentique"],
        flavors: ["NON"],
        sizes: ["0.6kg"],
        bestSeller: false
    },
    {
        id: 10,
        name: "Bulk Mass 5kg",
        category: "protein",
        price: 180,
        image: "https://res.cloudinary.com/dvq4ieugm/image/upload/v1772445831/gsn-products/1772445829634-bfeer_esp6zc.png",
        desc: ". PROTEIN COMPLEX    -MPC WPC WPI . ADVANCED PRO CARB MATRIX    -MALTODEXTRIN DEXTROSE-OAT FLOUR . ANABOLIC PERFORMANCE STACK    -25G EAA-5G CREATINE 1G TAURINE-0.5G DAA . VITAMINS & MINERALS   -13 VITAMINS 6 MINERALS",
        benefits: ["Produit authentique GSN", "Livraison rapide 24/48h", "100% Authentique"],
        flavors: ["Choco & vanilla milkshake"],
        sizes: ["5kg"],
        bestSeller: false
    },
    {
        id: 11,
        name: "BULK MASS 2.5Kg",
        category: "protein",
        price: 120,
        image: "https://res.cloudinary.com/dvq4ieugm/image/upload/v1771584316/gsn-products/1771584315323-Untitled_2sss_k4yima.png",
        desc: ". PROTEIN COMPLEX    -MPC WPC WPI . ADVANCED PRO CARB MATRIX    -MALTODEXTRIN DEXTROSE-OAT FLOUR . ANABOLIC PERFORMANCE STACK    -25G EAA-5G CREATINE 1G TAURINE-0.5G DAA . VITAMINS & MINERALS   -13 VITAMINS 6 MINERALS",
        benefits: ["Produit authentique GSN", "Livraison rapide 24/48h", "100% Authentique"],
        flavors: ["chocolate milkshake", "vanilla milkshake"],
        sizes: ["2.5kg"],
        bestSeller: false
    },
    {
        id: 12,
        name: "PROTEIN PANCAKE",
        category: "vitamins",
        price: 70,
        image: "https://res.cloudinary.com/dvq4ieugm/image/upload/v1764164092/gsn-products/1764164091710-CaptureAAA_rpbvpc.png",
        desc: "PROTEIN PANCAKE - Supplement sportif premium par GSN Tunisia.",
        benefits: ["Produit authentique GSN", "Livraison rapide 24/48h", "100% Authentique"],
        flavors: ["VANILLA"],
        sizes: ["1KG"],
        bestSeller: false
    },
    {
        id: 13,
        name: "CARBO MAX 3KG",
        category: "protein",
        price: 100,
        image: "https://res.cloudinary.com/dvq4ieugm/image/upload/v1764163600/gsn-products/1764163599118-CaptureAAA_vu9zed.png",
        desc: "CARBO MAX 3KG - Supplement sportif premium par GSN Tunisia.",
        benefits: ["Produit authentique GSN", "Livraison rapide 24/48h", "100% Authentique"],
        flavors: ["punch fruit"],
        sizes: ["3KG"],
        bestSeller: false
    },
    {
        id: 14,
        name: "CREATINE MONOHYDRATE 500G",
        category: "preworkout",
        price: 90,
        image: "https://res.cloudinary.com/dvq4ieugm/image/upload/v1763918288/gsn-products/1763918287088-Untitled_6_n3n3ee.png",
        desc: "CREATINE MONOHYDRATE 500G - Supplement sportif premium par GSN Tunisia.",
        benefits: ["Produit authentique GSN", "Livraison rapide 24/48h", "100% Authentique"],
        flavors: ["NO"],
        sizes: ["500G"],
        bestSeller: false
    },
    {
        id: 15,
        name: "CREAPURE MONOHYDRATE",
        category: "preworkout",
        price: 100,
        image: "https://res.cloudinary.com/dvq4ieugm/image/upload/v1763638956/gsn-products/1763638954436-716yJFKCftL_ugffzh.png",
        desc: "Creapure by Great Sport Nutrition is designed to boost strength, increase muscle mass, and speed up muscle recovery during workouts. It contains pure creatine monohydrate from Creapure, known for its outstanding quality and high purity, making it the perfect choice for athletes looking to enhance performance and energy during short, intense activities.",
        benefits: ["Produit authentique GSN", "Livraison rapide 24/48h", "100% Authentique"],
        flavors: ["Unflavored"],
        sizes: ["0.3kg"],
        bestSeller: false
    },
    {
        id: 16,
        name: "BETA ALANINE POWER",
        category: "preworkout",
        price: 60,
        image: "https://res.cloudinary.com/dvq4ieugm/image/upload/v1763547326/gsn-products/1763547325664-4_bbgpee.png",
        desc: "BETA ALANINE POWER 250G",
        benefits: ["Produit authentique GSN", "Livraison rapide 24/48h", "100% Authentique"],
        flavors: ["FRUIT PUNCH"],
        sizes: ["0.25kg"],
        bestSeller: false
    },
    {
        id: 17,
        name: "ARGININE BOOST",
        category: "preworkout",
        price: 60,
        image: "https://res.cloudinary.com/dvq4ieugm/image/upload/v1763547259/gsn-products/1763547258208-3_wsec1h.png",
        desc: "ARGININE BOOST",
        benefits: ["Produit authentique GSN", "Livraison rapide 24/48h", "100% Authentique"],
        flavors: ["FRUIT PUNCH"],
        sizes: ["0.25kg"],
        bestSeller: false
    },
    {
        id: 18,
        name: "CITRULLINE MALATE",
        category: "preworkout",
        price: 60,
        image: "https://res.cloudinary.com/dvq4ieugm/image/upload/v1763547194/gsn-products/1763547194071-5_ap55op.png",
        desc: "CITRULLINE",
        benefits: ["Produit authentique GSN", "Livraison rapide 24/48h", "100% Authentique"],
        flavors: ["FRUIT PUNCH"],
        sizes: ["0.25kg"],
        bestSeller: false
    },
    {
        id: 19,
        name: "GLUTAMINE",
        category: "preworkout",
        price: 60,
        image: "https://res.cloudinary.com/dvq4ieugm/image/upload/v1763546705/gsn-products/1763546704311-8_cu6vco.png",
        desc: "GLUTAMINE",
        benefits: ["Produit authentique GSN", "Livraison rapide 24/48h", "100% Authentique"],
        flavors: ["UNFLAVORED"],
        sizes: ["0.25kg"],
        bestSeller: false
    },
    {
        id: 20,
        name: "HYDRA FUEL",
        category: "preworkout",
        price: 60,
        image: "https://res.cloudinary.com/dvq4ieugm/image/upload/v1763546568/gsn-products/1763546567865-1_vloapc.png",
        desc: "HYDRA FUEL",
        benefits: ["Produit authentique GSN", "Livraison rapide 24/48h", "100% Authentique"],
        flavors: ["FRUIT PUNCH", "FRESH PINEAPPLE"],
        sizes: ["0.2kg"],
        bestSeller: false
    },
    {
        id: 21,
        name: "EAA EXTRA HYDRATION",
        category: "preworkout",
        price: 80,
        image: "https://res.cloudinary.com/dvq4ieugm/image/upload/v1763544527/gsn-products/1763544526409-6_onnhsv.png",
        desc: "EAA EXTRA HYDRATION - Supplement sportif premium par GSN Tunisia.",
        benefits: ["Produit authentique GSN", "Livraison rapide 24/48h", "100% Authentique"],
        flavors: ["FRUIT PUNCH"],
        sizes: ["0.45kg"],
        bestSeller: false
    },
    {
        id: 22,
        name: "Pre Workout",
        category: "preworkout",
        price: 90,
        image: "https://res.cloudinary.com/dvq4ieugm/image/upload/v1763480865/gsn-products/1763480864953-Capture114_tcstt3.png",
        desc: "Inferno Intense Pre-Workout is a comprehensive formula designed to enhance your training performance. It combines a blend of amino acids, vitamins, and minerals to support energy levels, focus, endurance, and muscle pumps.",
        benefits: ["Produit authentique GSN", "Livraison rapide 24/48h", "100% Authentique"],
        flavors: ["FRIUT PUNCH"],
        sizes: ["0.45kg"],
        bestSeller: false
    },
    {
        id: 23,
        name: "PRO ISOLATE",
        category: "protein",
        price: 140,
        image: "https://res.cloudinary.com/dvq4ieugm/image/upload/v1763040210/gsn-products/1763040209642-pi1_1_bbrla5.png",
        desc: "PRO ISO Whey GSN is a dietary supplement that promotes muscle growth and recovery after exercise. It is an ultra-pure whey protein isolate formula perfect for fitness enthusiasts and bodybuilders. Packed with essential amino acids and high in BCAAs. With low fat, carbs, and calories, it's an ideal choice for maintaining a lean physique. Mix it with liquids or use it in recipes. Suitable for lactose intolerant or dairy allergic individuals.",
        benefits: ["Produit authentique GSN", "Livraison rapide 24/48h", "100% Authentique"],
        flavors: ["CHOCOLATE", "VANILLA ICE CREAM", "STRAWBERRY ICE CREAM"],
        sizes: ["0.9kg", "1.6kg"],
        bestSeller: false
    },
    {
        id: 24,
        name: "Big Mass Gainer",
        category: "protein",
        price: 60,
        image: "https://res.cloudinary.com/dvq4ieugm/image/upload/v1762896007/gsn-products/1762896006150-3_ayxkey.png",
        desc: "GSN Gainer is a shake created especially for gaining muscle and weight. It combines carbs and amino acids to encourage the growth of muscle. With added creatine, it provides 3 grams of pure creatine daily. It contributes to the preservation and growth of muscle mass because it contains more than 80% whey protein. You can consume more calories thanks to its high-calorie formula, which provides 1351 calories each day.",
        benefits: ["Produit authentique GSN", "Livraison rapide 24/48h", "100% Authentique"],
        flavors: ["Chocolate", "Strawberry Ice Cream"],
        sizes: ["1kg", "3kg", "6kg"],
        bestSeller: false
    },
    {
        id: 25,
        name: "Pure Whey",
        category: "protein",
        price: 100,
        image: "https://res.cloudinary.com/dvq4ieugm/image/upload/v1762895815/gsn-products/1762895814619-2_nrtos5.png",
        desc: "The Pure whey GSN is high-protein instant powder preparation based on native whey protein concentrate. It's a mix of high-value protein with completely preserved nutritional qualities, cold extracted from dairy source of controlled and extremely pure origin.",
        benefits: ["Produit authentique GSN", "Livraison rapide 24/48h", "100% Authentique"],
        flavors: ["Chocolate", "Strawberry Ice Cream", "Vanilla ice cream"],
        sizes: ["0.9kg", "2kg"],
        bestSeller: false
    },
    {
        id: 26,
        name: "Complete Meal Replacement",
        category: "vitamins",
        price: 70,
        image: "https://res.cloudinary.com/dvq4ieugm/image/upload/v1764326568/gsn-products/1764326567262-WhatsApp_Image_2025-11-26_at_1.03q_dszdtm.png",
        desc: "GSN Complete Meal Replacement is a nutritious meal substitute that provides balanced energy, 27g of protein, 5.3g of fiber, and essential vitamins and minerals with no added sugar. Formulated with DigeZyme® for better digestion and nutrient absorption, it helps support muscle growth, satiety, and overall well-being perfect for active people and busy lifestyles.",
        benefits: ["Produit authentique GSN", "Livraison rapide 24/48h", "100% Authentique"],
        flavors: ["VANILLA CUPCAKE", "STRAWBERRY CAKE", "CHOCOLATE FUDGE"],
        sizes: ["1KG"],
        bestSeller: false
    },
    {
        id: 27,
        name: "Mega Vitamine",
        category: "pack",
        price: 80,
        image: "https://res.cloudinary.com/dvq4ieugm/image/upload/v1760976388/gsn-products/1760976387765-4_v91w6p.png",
        desc: "Multivitamins – supports overall vitality and immune health  Zinc Bisglycinate – promotes hormonal balance and recovery  Magnesium + B-Complex – aids energy production and reduces fatigue  Fish Oil (Omega-3) – supports cardiovascular, brain, and joint health",
        benefits: ["Produit authentique GSN", "Livraison rapide 24/48h", "100% Authentique"],
        flavors: ["Unflavored"],
        sizes: ["Standard"],
        bestSeller: false
    },
    {
        id: 28,
        name: "Big Mass Gainer & Creatine 200g",
        category: "pack",
        price: 150,
        image: "https://res.cloudinary.com/dvq4ieugm/image/upload/v1753634012/gsn-products/1753634011126-150_z0mu0r.png",
        desc: "Big Mass Gainer (3 kg) – supports rapid muscle and weight gain with high-quality calories and protein Creatine (200 g) – boosts strength, power, and workout performance",
        benefits: ["Produit authentique GSN", "Livraison rapide 24/48h", "100% Authentique"],
        flavors: ["Melted chocolate", "Vanilla ice cream", "Strawberry ice cream"],
        sizes: ["Standard"],
        bestSeller: true
    },
    {
        id: 29,
        name: "Big Mass Gainer & Multivitamin",
        category: "pack",
        price: 130,
        image: "https://res.cloudinary.com/dvq4ieugm/image/upload/v1764165184/gsn-products/1764165182459-1753634028008-140_omulnc_gtnuiy.png",
        desc: "Big Mass Gainer – promotes muscle growth and healthy weight gain with balanced nutrients Multivitamins – supports energy, recovery, and overall wellness",
        benefits: ["Produit authentique GSN", "Livraison rapide 24/48h", "100% Authentique"],
        flavors: ["Melted chocolate", "vanilla ice cream", "Strawberry ice cream"],
        sizes: ["Standard"],
        bestSeller: true
    },
    {
        id: 30,
        name: "Zink & Omega - 3 & Mag + B complex",
        category: "pack",
        price: 70,
        image: "https://res.cloudinary.com/dvq4ieugm/image/upload/v1753919904/gsn-products/1753919903518-Untitled-1_js0klu.png",
        desc: "Zinc Bisglycinate – supports immunity and hormonal balance Fish Oil (Omega-3) – promotes heart, brain, and joint health Magnesium + B-Complex – boosts energy metabolism and reduces fatigue",
        benefits: ["Produit authentique GSN", "Livraison rapide 24/48h", "100% Authentique"],
        flavors: ["Unflavored"],
        sizes: ["Standard"],
        bestSeller: false
    },
    {
        id: 31,
        name: "Zinc & Mag+ B complex",
        category: "pack",
        price: 40,
        image: "https://res.cloudinary.com/dvq4ieugm/image/upload/v1753919969/gsn-products/1753919967974-Untitled-2_ixksra.png",
        desc: "Zinc Bisglycinate – strengthens immunity and supports hormonal balance Magnesium + B-Complex – enhances energy production and reduces fatigue",
        benefits: ["Produit authentique GSN", "Livraison rapide 24/48h", "100% Authentique"],
        flavors: ["Unflavored"],
        sizes: ["Standard"],
        bestSeller: true
    },
    {
        id: 32,
        name: "Boost performance Plus",
        category: "pack",
        price: 100,
        image: "https://res.cloudinary.com/dvq4ieugm/image/upload/v1764165052/gsn-products/1764165051322-wi-fi-smart-phone-message-envelope-and-telephone-icon-set-free-vector_pgvtwu.png",
        desc: "Creatine (500 g) – increases strength, endurance, and muscle performance Multivitamins – supports energy, recovery, and overall health",
        benefits: ["Produit authentique GSN", "Livraison rapide 24/48h", "100% Authentique"],
        flavors: ["Unflavored"],
        sizes: ["Standard"],
        bestSeller: false
    },
    {
        id: 33,
        name: "Nitro muscles",
        category: "pack",
        price: 190,
        image: "https://res.cloudinary.com/dvq4ieugm/image/upload/v1764165291/gsn-products/1764165288401-1753634140355-n210_lgokxb_xf8bid.png",
        desc: "Nitro Whey – supports lean muscle growth and post-workout recovery Creatine (200 g) – enhances strength, power, and performance Multivitamins – promotes energy, immunity, and overall well-being",
        benefits: ["Produit authentique GSN", "Livraison rapide 24/48h", "100% Authentique"],
        flavors: ["Melted chocolate", "Vanilla ice cream"],
        sizes: ["Standard"],
        bestSeller: false
    },
    {
        id: 34,
        name: "MAG+ B-COMPLEX",
        category: "vitamins",
        price: 20,
        image: "https://res.cloudinary.com/dvq4ieugm/image/upload/v1753635253/gsn-products/1753635252351-17_tehodx.png",
        desc: "This advanced daily formula delivers 415 mg of highly  absorbable magnesium combined with a complete spectrum  of B-complex vitamins to help support energy metabolism,  maintain healthy muscle and nerve function, promote mental  focus, and reduce tiredness and fatigue.",
        benefits: ["Produit authentique GSN", "Livraison rapide 24/48h", "100% Authentique"],
        flavors: ["Unflavored"],
        sizes: ["Standard"],
        bestSeller: false
    },
    {
        id: 35,
        name: "ZINC BISGLYCINATE",
        category: "vitamins",
        price: 20,
        image: "https://res.cloudinary.com/dvq4ieugm/image/upload/v1753635161/gsn-products/1753635160234-20_y9rzua.png",
        desc: "Zinc Bisglycinate is a premium, chelated form of zinc known  for superior absorption and gentle digestion. It supports  immune health, skin repair, antioxidant defense, and healthy  hormone balance.",
        benefits: ["Produit authentique GSN", "Livraison rapide 24/48h", "100% Authentique"],
        flavors: ["Unflavored"],
        sizes: ["Standard"],
        bestSeller: false
    },
    {
        id: 36,
        name: "FISH OIL OMEGA-3",
        category: "vitamins",
        price: 30,
        image: "https://res.cloudinary.com/dvq4ieugm/image/upload/v1753635216/gsn-products/1753635215829-18_wvin5r.png",
        desc: "The omega 3 fatty acids EPA and DHA found in fish oils have  anti-inflammatory actions helping to support joint health,  reduce pain and stiffness and improve mobility. They also  contribute to the normal function of the heart and  maintenance of skin condition.",
        benefits: ["Produit authentique GSN", "Livraison rapide 24/48h", "100% Authentique"],
        flavors: ["Unflavored"],
        sizes: ["Standard"],
        bestSeller: false
    },
    {
        id: 37,
        name: "MONODOSE PURE WHEY",
        category: "protein",
        price: 70,
        image: "https://res.cloudinary.com/dvq4ieugm/image/upload/v1753635273/gsn-products/1753635272675-23_dxzal7.png",
        desc: "PRO ISO Whey GSN is a dietary supplement that promotes muscle growth and recovery after exercise. It is an ultra-pure whey protein isolate formula perfect for fitness enthusiasts and bodybuilders. Packed with essential amino acids and high in BCAAs. With low fat, carbs, and calories, it's an ideal choice for maintaining a lean physique. Mix it with liquids or use it in recipes. Suitable for lactose intolerant or dairy allergic individuals.",
        benefits: ["Produit authentique GSN", "Livraison rapide 24/48h", "100% Authentique"],
        flavors: ["MIX"],
        sizes: ["Standard"],
        bestSeller: true
    },
    {
        id: 38,
        name: "MONODOSE NITRO WHEY",
        category: "protein",
        price: 70,
        image: "https://res.cloudinary.com/dvq4ieugm/image/upload/v1753635289/gsn-products/1753635288029-22_vp87vd.png",
        desc: "The Nitro Whey GSN is a formula based on the most filtered and most assimilable protein sources with high biological value. This formula is enriched with creatine, each serving provides 2g of pure creatine per day. Which accelerates lean mass gain by improving the transport of amino-acids, making muscle cells stronger and activating the muscle recovery process.",
        benefits: ["Produit authentique GSN", "Livraison rapide 24/48h", "100% Authentique"],
        flavors: ["Unflavored"],
        sizes: ["Standard"],
        bestSeller: false
    },
    {
        id: 39,
        name: "MONODOSE PRO ISOLATE",
        category: "protein",
        price: 80,
        image: "https://res.cloudinary.com/dvq4ieugm/image/upload/v1753635305/gsn-products/1753635304187-21_hkd105.png",
        desc: "PRO ISO Whey GSN is a dietary supplement that promotes muscle growth and recovery after exercise. It is an ultra-pure whey protein isolate formula perfect for fitness enthusiasts and bodybuilders. Packed with essential amino acids and high in BCAAs. With low fat, carbs, and calories, it's an ideal choice for maintaining a lean physique. Mix it with liquids or use it in recipes. Suitable for lactose intolerant or dairy allergic individuals.",
        benefits: ["Produit authentique GSN", "Livraison rapide 24/48h", "100% Authentique"],
        flavors: ["Unflavored"],
        sizes: ["Standard"],
        bestSeller: false
    },
    {
        id: 40,
        name: "MULTIVITAMIN",
        category: "vitamins",
        price: 20,
        image: "https://res.cloudinary.com/dvq4ieugm/image/upload/v1753635430/gsn-products/1753635429205-21.5_xyhktx.png",
        desc: "This multivitamin provides essential vitamins and minerals at 300% of the daily requirement. It includes a full range of B-complex vitamins, A, C, D, E, and K. Also contains key minerals like Iron, Zinc, lodine, Copper, and Manganese. Designed to support energy, immunity, and overall daily wellness. Ideal for filling dietary gaps or increased nutritional needs.",
        benefits: ["Produit authentique GSN", "Livraison rapide 24/48h", "100% Authentique"],
        flavors: ["Unflavored"],
        sizes: ["Standard"],
        bestSeller: false
    },
    {
        id: 41,
        name: "CREATINE MONOHYDRATE",
        category: "preworkout",
        price: 50,
        image: "https://res.cloudinary.com/dvq4ieugm/image/upload/v1763918094/gsn-products/1763918093267-Untitled-1_rs5ptc.png",
        desc: "Creatine contributes to improved muscle performance, promotes muscle strength and power, and ensures better recovery during successive short-duration, high-intensity strength exercises.* For adults over 55, creatine can enhance the effect of resistance training on muscle strength.",
        benefits: ["Produit authentique GSN", "Livraison rapide 24/48h", "100% Authentique"],
        flavors: ["UNFLAVORED"],
        sizes: ["0.2kg"],
        bestSeller: true
    },
    {
        id: 42,
        name: "NITRO WHEY",
        category: "protein",
        price: 170,
        image: "https://res.cloudinary.com/dvq4ieugm/image/upload/v1752706966/gsn-products/1752706966161-3_j8v0cr.png",
        desc: "The Nitro Whey GSN is a formula based on the most filtered and most assimilable protein sources with high biological value. This formula is enriched with creatine, each serving provides 2g of pure creatine per day. Which accelerates lean mass gain by improving the transport of amino-acids, making muscle cells stronger and activating the muscle recovery process.",
        benefits: ["Produit authentique GSN", "Livraison rapide 24/48h", "100% Authentique"],
        flavors: ["Chocolate", "Strawberry Ice Cream", "Vanilla ice cream"],
        sizes: ["Standard"],
        bestSeller: false
    }
];
